vim.o.compatible = false
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.signcolumn = number
vim.o.background = "dark"
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.autochdir = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
